### ISSUE TITLE
Python throws PlagiarismError in Mint 17

### ISSUE THREAD

**Issue by parakalan** [yagneshlp/SWLogin#1]
If you want to contribute to a repo, fork it and submit a pull request.

**Comment by yagneshlp** [comment]
Sorry, I'm New to VCS, which might have been evident by just 2 repos in my profile. 

Isn't an clause  of a MIT License to Permit "to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software".
I have clearly mentioned the Repo this was originally from, and it even keeps on mentioning it every single time the program is run. 

I have neither Stolen someone's work, and have not claimed it as my "Original Work".  

Now that you have mentioned, i made myself familiar with how VCS works and I will do the needful. 
Thanks for pointing it out!
